-- 17. From the following table, write a SQL query to determine the maximum order (purchase) amount generated by each salesperson. Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.). Return salesperson id and maximum purchase amount.
select max(purch_amt),salesman_id from orders
where salesman_id between 5003 and 5008
group by salesman_id